### PR TITLE
refresh slim after adding terms for OBA

### PR DESCRIPTION
**Pull request by rays22**
@matentzn , I have no write access to this repo.
Addresses https://github.com/obophenotype/bio-attribute-ontology/issues/257

### CODE REVIEW

**Comment by matentzn** [comment]
I gave the whole phenotype editors access now, can you check? (I also invited you to the team)

**Comment by rays22** [comment]
> I gave the whole phenotype editors access now, can you check? (I also invited you to the team)

Thanks @matentzn , yes, I have write access now.

**Review by gouttegd — COMMENTED** [review]
Could you sort the seed file?

A plain `sort(1)` would do:

```sh
sort seed.txt > sorted.txt
mv sorted.txt seed.txt
```

**Comment by gouttegd** [comment]
Now that I think of it: @matentzn Is sorting the file really necessary? The extraction step does not seem to have any trouble creating the slim even with an unsorted seed file.

**Review by gouttegd — APPROVED** [review]
Thanks @rays22 ! All good, if you have been given write access you can go ahead and merge.

**Comment by matentzn** [comment]
Its not necessary to order, but what I would like to avoid is people adding duplicate ids in there; but even that is no drama.

**Pull request merged**
