### PR TITLE
Add terms for maxo

### PR DESCRIPTION
**Pull request by LCCarmody**
Added these terms for use add CHEBI_131795,CHEBI:133326, CHEBI:143001,CHEBI:145515,CHEBI:177023, CHEBI:32184, CHEBI:50664, CHEBI:51065, CHEBI:73273, CHEBI:91016

### CODE REVIEW

**Review by rays22 — APPROVED** [review]

**Review by matentzn — CHANGES_REQUESTED** [review]
The diff of seed.txt is too large - I dont know why.. 

@rays22 I agree that the PR looks correct, but large diffs are a bad small and should be fixed.. Can you help @LCCarmody to sort this? Is it file endings? Sort order?

**Comment by rays22** [comment]
> The diff of seed.txt is too large - I dont know why..
> 
> @rays22 I agree that the PR looks correct, but large diffs (seed.txt) are a bad small and should be fixed.. Can you help @LCCarmody to sort this? Is it file endings? Sort order?

I had checked that the sorting is OK before approving the PR. However, I did not check the [line endings:](https://en.wikipedia.org/wiki/Newline). :)
The large diff is indeed caused by the different [line endings:](https://en.wikipedia.org/wiki/Newline)
* `main` branch: Linefeed (LF, unix-style)
* `addtermsforMAXO` branch: Carriage return-linefeed (CR-LF; windows-style)
line_endings

@LCCarmody , in many text editors you can set the line endings to follow unix-standards, but I do not know which editor in   what OS you are using.
You may want to run
```sh
sh odk.sh make all
```
again with the `seed.txt` file modified by me before merging this PR.

**Comment by LCCarmody** [comment]
ah! I know what happened, but I am not sure how to make sure this doesn't happen in the future. I opened in standard text editor, but it wouldn't allow me to sort. So I opened in Excel, sorted, and saved as txt. I assume that's how the line endings got introduced.

Do you have a text editor that allows sorting and will not introduce different line endings?

**Comment by rays22** [comment]
> Do you have a text editor that allows sorting and will not introduce different line endings?

@LCCarmody ,
I use `Vim` :grinning: (or one of its variants: gvim, [macvim](https://macvim.org/), [vimr](https://github.com/qvacua/vimr), [neovim](https://neovim.io/)), because it is free and works on almost all operating systems and also on the command line. However,`Vim` has a steep learning curve.
Here is [a list of easier to learn alternatives to VIM.](https://www.techradar.com/best/best-text-editors)

**Review by LCCarmody — COMMENTED** [review]
I believe I changed everything back to LF

**Review by matentzn — APPROVED** [review]

**Comment by LCCarmody** [comment]
Sorry, it took me a bit to fix it. I was able to convert it Geany (just took me a bit to find it). Okay to merge?

**Pull request merged**
